import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

// Get __dirname equivalent for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Less compiler and CSS bundler plugin
const stylePlugin = {
  name: 'style-plugin',
  setup(build) {
    // Always build styles when running the build
    let shouldBuildStyles = true;
    
    // Build styles at the end
    build.onEnd(async () => {
      if (shouldBuildStyles) {
        console.log('🔄 Building styles...');
        
        try {
          const mainLessPath = join(__dirname, 'src/styles/main.less');
          if (!existsSync(mainLessPath)) {
            console.log('ℹ️  No main.less file found, skipping style build');
            return;
          }
          
          // Dynamically import Less
          const less = await import('less');
          const source = readFileSync(mainLessPath, 'utf8');
          
          const result = await less.default.render(source, {
            filename: mainLessPath,
            paths: [dirname(mainLessPath)],
            compress: prod
          });
          
          writeFileSync('styles.css', result.css);
          console.log(`✅ Styles built successfully! (${Math.round(result.css.length / 1024)} KB)`);
          
        } catch (error) {
          console.error('❌ Style build failed:');
          console.error(error.message);
        }
      }
    });
  }
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [stylePlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
