import type { App } from 'obsidian';
import type { ChatMessage, ConversationSummary, AgentTokenBreakdown, QuickAskTurn } from './services/chat-stream';
import type { TokenUsage } from './services/llm-provider';
import type { InsightCardState } from './services/insights';
import type { SuggestionCardState } from './services/suggestions';
import type { TodoState } from './services/tools/todo-state';
import type { GeneratedAsset } from './services/generated-asset-collection';

type ReadonlyChatMessages = ReadonlyArray<ChatMessage>;

/** Session metadata (stored in list.json) */
export interface SessionMetadata {
    id: string;
    /** Session title, empty string means "use firstUserMessage as display title" */
    title: string;
    /** First user message content (truncated for display), stored for quick access without loading full messages */
    firstUserMessage: string;
    tokenUsage: TokenUsage;
    createdAt: number;
    updatedAt: number;
    /** Draft input content (unsent text in input box), restored when loading session */
    draftInput?: string;
    /**
     * Last terminal state of the insight preview card. Persisted by
     * {@link SessionRuntime} after each successful (or failed) insight
     * extraction so that switching away and back to the session — or
     * reloading the plugin entirely — restores the card without
     * re-running the LLM call. Bound to a specific assistant
     * `messageId` so stale states are detectable on replay.
     *
     * `loading` is deliberately not persisted (it's transient).
     */
    lastInsights?: InsightCardState;

    /**
     * Last terminal state of the follow-up suggestion bar, produced
     * by the LLM fallback extraction. Persisted by {@link SessionRuntime}
     * so the bar survives view detach and plugin reload. Mirrors
     * {@link lastInsights} in shape and lifecycle.
     */
    lastSuggestions?: SuggestionCardState;
}

/** Messages file content (stored in sessions/${id}.json) */
interface SessionMessagesFile {
    /**
     * File schema version.
     * - v1–v4: deprecated. Sessions with these versions are purged on
     *          load (file deleted, metadata removed).
     * - v5: reshapes each TODO item to carry TWO required strings —
     *       `brief` (short user-facing summary) and `content` (long
     *       machine-facing task spec).
     * - v6: adds `quickAskTurns` (QuickAsk side-conversation pairs persisted
     *       separately from the main message flow).
     * - v7: adds `toolCallAssets` (top-level session field listing assets
     *       generated by tool calls, moved from ChatMessage.toolCallAssets).
     */
    version: 5 | 6 | 7;
    id: string;
    messages: ChatMessage[];
    /** Top-level generated-asset records (v7+). Peer to messages, moved
     *  from per-message `toolCallAssets` to a session-level collection. */
    toolCallAssets?: GeneratedAsset[];
    /** Conversation summaries for context compression (persisted separately from messages) */
    summaries?: ConversationSummary[];
    /**
     * Sub-agent messages produced during delegate_task invocations, keyed by
     * the parent delegate_task toolCallId. Used by the UI to re-render inline
     * sub-agent bubbles after a session reload.
     */
    subAgentMessages?: Record<string, ChatMessage[]>;
    /**
     * Per-agent token usage split (main + each sub-agent by name).
     * Only produced by multi-agent sessions; absent for single-agent
     * (ChatStream) sessions.
     */
    agentTokenBreakdown?: AgentTokenBreakdown;
    /**
     * TODO state maintained by the `manage_todos` tool. Persisted so
     * the pinned panel + the model's view of in-progress subtasks
     * survive reloads. Absent / empty list is treated as "no todos"
     * by the loader.
     */
    todos?: TodoState;
    /**
     * QuickAsk side-turns persisted separately from the main message
     * flow. Each entry is a user→assistant question/answer pair
     * anchored to a specific assistant message. Absent in v5
     * files (treated as empty). Added in v6.
     */
    quickAskTurns?: QuickAskTurn[];
}

/** List file content (stored in sessions/list.json) */
interface SessionListFile {
    version: 1;
    activeSessionId: string;
    nextId: number;
    sessions: SessionMetadata[];
}

/** Global cumulative token statistics (stored in sessions/statistics.json) */
interface GlobalTokenStatisticsFile {
    version: 1;
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
}

/** Snapshot of a session (full data for backward compatibility with public API) */
export interface SessionSnapshot {
    id: string;
    title: string;
    firstUserMessage: string;
    messages: ChatMessage[];
    tokenUsage: TokenUsage;
    createdAt: number;
    updatedAt: number;
}

/**
 * Session manager with persistent storage and lazy loading.
 * - Metadata is stored in `sessions/list.json`
 * - Messages are stored in `sessions/${id}.json` (loaded on demand)
 */
export class SessionManager {
    /** Session metadata map */
    private metadataMap: Map<string, SessionMetadata> = new Map();
    /** Loaded messages cache */
    private messagesCache: Map<string, ChatMessage[]> = new Map();
    /** Loaded summaries cache for context compression */
    private summariesCache: Map<string, ConversationSummary[]> = new Map();
    /** Loaded sub-agent messages cache, keyed by sessionId, then by parent toolCallId */
    private subAgentMessagesCache: Map<string, Record<string, ChatMessage[]>> = new Map();
    /** Loaded per-agent token usage breakdown cache, keyed by sessionId */
    private agentTokenBreakdownCache: Map<string, AgentTokenBreakdown> = new Map();
    /**
     * Loaded TODO state cache, keyed by sessionId. Absent entry means
     * "no todos for this session" — callers should not rely on a
     * sentinel empty state from this map.
     */
    private todosCache: Map<string, TodoState> = new Map();
    /** Loaded QuickAsk side-turns cache, keyed by sessionId (v6+). */
    private quickAskTurnsCache: Map<string, QuickAskTurn[]> = new Map();
    /** Loaded generated-asset records, keyed by sessionId (v7+). */
    private toolCallAssetsCache: Map<string, GeneratedAsset[]> = new Map();
    /** Set of session IDs whose messages have been loaded */
    private loadedMessages: Set<string> = new Set();

    /** Global cumulative token usage across all sessions, persisted in statistics.json */
    private _globalTokenStats: TokenUsage = { promptTokens: 0, completionTokens: 0, totalTokens: 0 };

    /**
     * Sequential write chain to prevent concurrent file writes (list.json + session files).
     *
     * Every write operation is appended to this chain rather than racing via a
     * bare boolean / null-check mutex. This eliminates the TOCTOU gap between
     * "await previous save" and "assign new save" that existed in the old
     * `savePromise` pattern. Each work item reads its snapshot right before
     * performing I/O, so state changes that happen during an earlier write
     * (e.g. `createSession()` adding a new session) are always visible to the
     * next writer in the chain.
     *
     * The `.then(fn, fn)` dual-handler form ensures a single failing write
     * (e.g. disk full) does not poison the chain — subsequent callers still
     * execute their own work.
     */
    private writeChain: Promise<void> = Promise.resolve();

    private _activeSessionId: string;
    private _nextId = 1;
    private readonly app: App;
    private sessionsDir: string;
    private listFilePath: string;
    private statisticsFilePath: string;
    private cacheLoaded = false;

    /**
     * @param app        Obsidian app handle.
     * @param sessionsDir Vault-relative directory where session files live.
     *                    Resolved by the caller (typically `plugin.paths.sessions()`)
     *                    so this class stays agnostic of the plugin layout.
     */
    constructor(app: App, sessionsDir: string) {
        this.app = app;
        this.sessionsDir = sessionsDir;
        this.listFilePath = `${this.sessionsDir}/list.json`;
        this.statisticsFilePath = `${this.sessionsDir}/statistics.json`;
        this._activeSessionId = this.createSession();
    }

    get activeSessionId(): string {
        return this._activeSessionId;
    }

    get sessionCount(): number {
        return this.metadataMap.size;
    }

    /** Get the global cumulative token usage across all sessions */
    getGlobalTokenUsage(): TokenUsage {
        return { ...this._globalTokenStats };
    }

    /** Get all sessions sorted by updatedAt (most recent first) - metadata only, no messages */
    getAllSessions(): SessionSnapshot[] {
        return Array.from(this.metadataMap.values())
            .sort((a, b) => b.updatedAt - a.updatedAt)
            .map(meta => this.metadataToSnapshot(meta));
    }

    /** Get a session snapshot by ID (loads messages if not cached) */
    async getSession(id: string): Promise<SessionSnapshot | undefined> {
        const meta = this.metadataMap.get(id);
        if (!meta) return undefined;
        await this.loadMessages(id);
        return this.metadataToSnapshot(meta);
    }

    /** Get session snapshot synchronously (returns undefined if messages not loaded) */
    getSessionSync(id: string): SessionSnapshot | undefined {
        const meta = this.metadataMap.get(id);
        if (!meta) return undefined;
        if (!this.loadedMessages.has(id)) return undefined;
        return this.metadataToSnapshot(meta);
    }

    /**
     * One-line display label from in-memory metadata only (no messages file read).
     * Same rule as the session toolbar: non-empty `title`, else non-empty `firstUserMessage`,
     * else `""` when the session exists but has no label yet.
     *
     * @returns `undefined` if `sessionId` is not in the registry (e.g. session removed).
     */
    getSessionMetadataDisplayLine(sessionId: string): string | undefined {
        const meta = this.metadataMap.get(sessionId);
        if (!meta) return undefined;
        const title = meta.title.trim();
        if (title.length > 0) return title;
        const first = meta.firstUserMessage.trim();
        if (first.length > 0) return first;
        return "";
    }

    /** Get the active session snapshot (loads messages if not cached) */
    async getActiveSession(): Promise<SessionSnapshot | undefined> {
        return this.getSession(this._activeSessionId);
    }

    /** Get active session synchronously (returns undefined if messages not loaded) */
    getActiveSessionSync(): SessionSnapshot | undefined {
        return this.getSessionSync(this._activeSessionId);
    }

    /** Convert metadata to snapshot (uses cached messages) */
    private metadataToSnapshot(meta: SessionMetadata): SessionSnapshot {
        return {
            id: meta.id,
            title: meta.title,
            firstUserMessage: meta.firstUserMessage,
            messages: this.messagesCache.get(meta.id) ?? [],
            tokenUsage: { ...meta.tokenUsage },
            createdAt: meta.createdAt,
            updatedAt: meta.updatedAt,
        };
    }

    /** Create a new empty session and make it active. Returns the new session ID. */
    createSession(): string {
        const id = `session-${this._nextId++}`;
        const now = Date.now();
        const meta: SessionMetadata = {
            id,
            title: '',
            firstUserMessage: '',
            tokenUsage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
            createdAt: now,
            updatedAt: now,
        };
        this.metadataMap.set(id, meta);
        this.messagesCache.set(id, []);
        this.loadedMessages.add(id);
        this._activeSessionId = id;
        return id;
    }

    /** Set the title of the active session */
    setTitle(title: string): void {
        this.setSessionTitle(this._activeSessionId, title);
    }

    /**
     * Set the title of a specific session by id. Used by background
     * SessionRuntime instances that finish their turn after the view
     * has switched away — they need to write into their own metadata,
     * not whichever session happens to be active.
     */
    setSessionTitle(sessionId: string, title: string): void {
        const meta = this.metadataMap.get(sessionId);
        if (meta) {
            meta.title = title;
        }
    }

    /** Get the draft input from the active session */
    getDraftInput(): string {
        const meta = this.metadataMap.get(this._activeSessionId);
        return meta?.draftInput ?? '';
    }

    /** Set the draft input for the active session */
    setDraftInput(draft: string): void {
        const meta = this.metadataMap.get(this._activeSessionId);
        if (meta) {
            meta.draftInput = draft;
        }
    }

    /**
     * Get the persisted insight card state for a specific session, or
     * undefined if none has been recorded (or the session no longer
     * exists). Used by SessionRuntime on hydration / by the view on
     * cold-load replay.
     */
    getSessionLastInsights(sessionId: string): InsightCardState | undefined {
        return this.metadataMap.get(sessionId)?.lastInsights;
    }

    /**
     * Record (or clear) the insight card state for a specific session.
     * Pass `undefined` to clear. Calls with `state.phase === 'loading'`
     * are ignored on purpose — loading is a transient runtime-only
     * state that should never round-trip through disk.
     *
     * Only mutates in-memory metadata; callers should follow up with
     * {@link saveMetadata} (or rely on the next {@link saveToCache})
     * to flush to disk.
     */
    setSessionLastInsights(sessionId: string, state: InsightCardState | undefined): void {
        const meta = this.metadataMap.get(sessionId);
        if (!meta) return;
        if (state && state.phase === 'loading') return;
        if (state) {
            meta.lastInsights = state;
        } else {
            delete meta.lastInsights;
        }
    }

    /** Convenience: clear the insight card state for a specific session. */
    clearSessionLastInsights(sessionId: string): void {
        this.setSessionLastInsights(sessionId, undefined);
    }

    /**
     * Get the persisted suggestion bar state for a specific session,
     * or undefined if none has been recorded. Mirrors
     * {@link getSessionLastInsights}.
     */
    getSessionLastSuggestions(sessionId: string): SuggestionCardState | undefined {
        return this.metadataMap.get(sessionId)?.lastSuggestions;
    }

    /**
     * Record (or clear) the suggestion bar state for a specific session.
     * Pass `undefined` to clear. Calls with `state.phase === 'loading'`
     * are ignored — loading is a transient runtime-only state.
     *
     * Only mutates in-memory metadata; callers should follow up with
     * {@link saveMetadata} to flush to disk.
     */
    setSessionLastSuggestions(sessionId: string, state: SuggestionCardState | undefined): void {
        const meta = this.metadataMap.get(sessionId);
        if (!meta) return;
        if (state && state.phase === 'loading') return;
        if (state) {
            meta.lastSuggestions = state;
        } else {
            delete meta.lastSuggestions;
        }
    }

    /** Convenience: clear the suggestion bar state for a specific session. */
    clearSessionLastSuggestions(sessionId: string): void {
        this.setSessionLastSuggestions(sessionId, undefined);
    }

    /**
     * Get the persisted TODO state for a specific session. Returns
     * `undefined` when nothing is on file (the session predates v4 or
     * the model never wrote anything). Callers that need a guaranteed
     * non-null snapshot should fall back to `emptyTodoState()`.
     */
    getSessionTodos(sessionId: string): TodoState | undefined {
        return this.todosCache.get(sessionId);
    }

    /**
     * Record the TODO state for a specific session. Pass `undefined`
     * or a state with an empty `items` array to clear the entry.
     *
     * Only mutates in-memory caches; the next {@link saveToCache}
     * (or `runtime.persist`) flushes to disk.
     */
    setSessionTodos(sessionId: string, state: TodoState | undefined): void {
        if (!this.metadataMap.has(sessionId)) return;
        if (!state || state.items.length === 0) {
            this.todosCache.delete(sessionId);
            return;
        }
        // Defensive clone so callers can't accidentally mutate the
        // cached snapshot after handing it off.
        this.todosCache.set(sessionId, {
            items: state.items.map(item => ({ ...item })),
            updatedAt: state.updatedAt,
        });
    }

    /** Convenience: clear the TODO state for a specific session. */
    clearSessionTodos(sessionId: string): void {
        this.setSessionTodos(sessionId, undefined);
    }

    /**
     * Get QuickAsk side-turns for the active session. Returns `undefined`
     * when nothing is on file (session predates v6 or has no side-turns).
     */
    getQuickAskTurns(): QuickAskTurn[] | undefined {
        return this.quickAskTurnsCache.get(this._activeSessionId);
    }

    /**
     * Get generated-asset records for a specific session (v7+).
     * Returns `undefined` when nothing is on file (session predates
     * v7 or no assets were generated).
     */
    getSessionToolCallAssets(sessionId: string): GeneratedAsset[] | undefined {
        return this.toolCallAssetsCache.get(sessionId);
    }

    /** Get the first user message content from the active session */
    getFirstUserMessage(): string | null {
        const messages = this.messagesCache.get(this._activeSessionId);
        if (!messages) return null;
        const firstUserMsg = messages.find(m => m.role === 'user');
        return firstUserMsg?.content ?? null;
    }

    /**
     * Save a session's state into the in-memory caches by explicit id,
     * independent of `activeSessionId`. This is the back-end used by both
     * the active-session shortcut above and by background SessionRuntime
     * instances that need to persist their progress after the view has
     * already switched away from them.
     *
     * Only updates the in-memory caches + metadata; callers still need to
     * invoke {@link saveToCache} (or one of its triggers) to flush to disk.
     */
    async saveSession(
        sessionId: string,
        currentMessages: ReadonlyChatMessages,
        currentTokenUsage: TokenUsage,
        summaries?: ConversationSummary[],
        subAgentMessages?: Record<string, ChatMessage[]>,
        agentTokenBreakdown?: AgentTokenBreakdown,
        todos?: TodoState,
        quickAskTurns?: QuickAskTurn[],
        toolCallAssets?: GeneratedAsset[],
    ): Promise<void> {
        const meta = this.metadataMap.get(sessionId);
        if (!meta) return;

        // Update messages cache
        this.messagesCache.set(sessionId, [...currentMessages]);
        this.loadedMessages.add(sessionId);

        // Update summaries cache
        if (summaries && summaries.length > 0) {
            this.summariesCache.set(sessionId, summaries.map(s => ({ ...s })));
        }

        // Update sub-agent messages cache (undefined means "no change";
        // pass an empty object to explicitly clear)
        if (subAgentMessages !== undefined) {
            if (Object.keys(subAgentMessages).length > 0) {
                this.subAgentMessagesCache.set(sessionId, subAgentMessages);
            } else {
                this.subAgentMessagesCache.delete(sessionId);
            }
        }

        // Update per-agent token usage breakdown cache (undefined means "no
        // change"; the orchestrator's getter always returns an object, and
        // single-agent ChatStream will simply never pass it).
        if (agentTokenBreakdown !== undefined) {
            const hasAny = Object.keys(agentTokenBreakdown.subAgents).length > 0
                || agentTokenBreakdown.main.totalTokens > 0;
            if (hasAny) {
                this.agentTokenBreakdownCache.set(sessionId, {
                    main: { ...agentTokenBreakdown.main },
                    subAgents: Object.fromEntries(
                        Object.entries(agentTokenBreakdown.subAgents).map(([k, v]) => [k, { ...v }]),
                    ),
                });
            } else {
                this.agentTokenBreakdownCache.delete(sessionId);
            }
        }

        // Update TODO state cache (undefined means "no change"; an
        // empty list explicitly clears, mirroring the subAgentMessages
        // convention). Defensive clone so the caller's snapshot stays
        // independent from the cache.
        if (todos !== undefined) {
            this.setSessionTodos(sessionId, todos);
        }

        // Update side-turns cache (undefined means "no change";
        // pass an empty array to explicitly clear).
        if (quickAskTurns !== undefined) {
            if (quickAskTurns.length > 0) {
                this.quickAskTurnsCache.set(sessionId, quickAskTurns.map(t => ({ ...t })));
            } else {
                this.quickAskTurnsCache.delete(sessionId);
            }
        }

        // Update generated-asset collection (v7+; undefined means "no
        // change"; pass an empty array to explicitly clear).
        if (toolCallAssets !== undefined) {
            if (toolCallAssets.length > 0) {
                this.toolCallAssetsCache.set(sessionId, [...toolCallAssets]);
            } else {
                this.toolCallAssetsCache.delete(sessionId);
            }
        }

        // Update firstUserMessage if not already set
        if (!meta.firstUserMessage && currentMessages.length > 0) {
            const firstUserMsg = currentMessages.find(m => m.role === 'user');
            if (firstUserMsg) {
                meta.firstUserMessage = firstUserMsg.content.slice(0, 100);
            }
        }

        // Compute delta vs previous metadata and accumulate into global stats.
        // Only positive deltas are applied — token usage is monotonic within a
        // session, so a negative delta would indicate a bug; clamping prevents
        // the global stats from going out of sync.
        const prev = meta.tokenUsage;
        this._globalTokenStats.promptTokens += Math.max(0, currentTokenUsage.promptTokens - prev.promptTokens);
        this._globalTokenStats.completionTokens += Math.max(0, currentTokenUsage.completionTokens - prev.completionTokens);
        this._globalTokenStats.totalTokens += Math.max(0, currentTokenUsage.totalTokens - prev.totalTokens);

        meta.tokenUsage = { ...currentTokenUsage };
        meta.updatedAt = Date.now();
    }

    /** Get sub-agent messages for the active session */
    getSubAgentMessages(): Record<string, ChatMessage[]> | undefined {
        return this.subAgentMessagesCache.get(this._activeSessionId);
    }

    /** Get per-agent token usage breakdown for the active session (v3+ only). */
    getAgentTokenBreakdown(): AgentTokenBreakdown | undefined {
        return this.agentTokenBreakdownCache.get(this._activeSessionId);
    }

    /** Get summaries for the active session */
    getSummaries(): ConversationSummary[] {
        return this.summariesCache.get(this._activeSessionId) ?? [];
    }

    /** Set summaries for the active session */
    setSummaries(summaries: ConversationSummary[]): void {
        this.summariesCache.set(this._activeSessionId, summaries.map(s => ({ ...s })));
    }

    /** Get summaries for a specific session */
    getSessionSummaries(sessionId: string): ConversationSummary[] {
        return this.summariesCache.get(sessionId) ?? [];
    }

    /**
     * Branch off a new session from an existing session at a given user-message
     * anchor. The new session is initialised with the prefix of messages that
     * appear BEFORE the anchor (so the anchor's user input goes back into the
     * draft, ready to be edited and resent), and every other piece of session
     * state — token usage, summaries, sub-agent messages, agent token
     * breakdown, title, firstUserMessage — starts fresh, exactly as if the
     * user had created a brand-new session.
     *
     * The newly-created session is registered in {@link metadataMap} but is
     * NOT made the active session here. The caller is expected to drive the
     * usual switch flow (detach old runtime → `switchTo(newId)` → bind),
     * which keeps the view layer in charge of UI transitions.
     *
     * @returns `{ newSessionId, draftInput }` on success, or `null` when the
     *          source session is missing or the anchor is not a user message
     *          inside it.
     */
    async branchSession(
        sourceId: string,
        anchorMessageId: string,
    ): Promise<{ newSessionId: string; draftInput: string } | null> {
        const sourceMeta = this.metadataMap.get(sourceId);
        if (!sourceMeta) return null;

        // Ensure source messages are available before slicing.
        await this.loadMessages(sourceId);
        const sourceMessages = this.messagesCache.get(sourceId) ?? [];

        const anchorIdx = sourceMessages.findIndex(m => m.id === anchorMessageId);
        if (anchorIdx < 0) return null;
        const anchor = sourceMessages[anchorIdx]!;
        if (anchor.role !== 'user') return null;

        // Slice messages BEFORE the anchor; the anchor itself goes to draft.
        // Shallow-clone each entry and force `streaming: false` so the new
        // session never shares mutable state with the source.
        const prefix = sourceMessages.slice(0, anchorIdx).map(m => ({
            ...m,
            streaming: false,
        }));

        // Snapshot active id around createSession() — that helper sets itself
        // active as a side effect, but branchSession promises only to create
        // the session, leaving switching to the caller.
        const prevActive = this._activeSessionId;
        const newId = this.createSession();
        this._activeSessionId = prevActive;

        // Seed the new session with the prefix and the draft.
        const newMeta = this.metadataMap.get(newId);
        if (newMeta) {
            newMeta.draftInput = anchor.content;
            if (prefix.length > 0) {
                const firstUserMsg = prefix.find(m => m.role === 'user');
                if (firstUserMsg) {
                    newMeta.firstUserMessage = firstUserMsg.content.slice(0, 100);
                }
            }
        }
        this.messagesCache.set(newId, prefix);
        this.loadedMessages.add(newId);

        return { newSessionId: newId, draftInput: anchor.content };
    }

    /** Switch to a different session by ID. Returns true if successful. */
    async switchTo(targetId: string): Promise<boolean> {
        if (this.metadataMap.has(targetId) && targetId !== this._activeSessionId) {
            this._activeSessionId = targetId;
            // Persist activeSessionId change to list.json — must go through
            // the write chain so concurrent background saves do not race.
            await this.saveMetadata();
            return true;
        }
        return false;
    }

    /**
     * Delete a session by ID. Removes session from memory, saves list.json,
     * and deletes the messages file. Messages file deletion failure does not
     * affect the result.
     *
     * If the deleted session was the active one, its ID is cleared from the
     * active-session slot so that the caller (typically the session navigator)
     * can decide which session to switch to next.
     *
     * Returns true if the session was found and deleted, false otherwise.
     */
    async deleteSession(id: string): Promise<boolean> {
        if (!this.metadataMap.has(id)) return false;

        const wasActive = id === this._activeSessionId;

        // Deduct the session's token usage from global stats before removing metadata
        const meta = this.metadataMap.get(id)!;
        this._globalTokenStats.promptTokens = Math.max(0,
            this._globalTokenStats.promptTokens - meta.tokenUsage.promptTokens);
        this._globalTokenStats.completionTokens = Math.max(0,
            this._globalTokenStats.completionTokens - meta.tokenUsage.completionTokens);
        this._globalTokenStats.totalTokens = Math.max(0,
            this._globalTokenStats.totalTokens - meta.tokenUsage.totalTokens);

        this.metadataMap.delete(id);

        // Clean up messages cache
        this.messagesCache.delete(id);
        this.loadedMessages.delete(id);
        // Clean up summaries cache
        this.summariesCache.delete(id);
        // Clean up sub-agent messages cache
        this.subAgentMessagesCache.delete(id);
        // Clean up per-agent token usage breakdown cache
        this.agentTokenBreakdownCache.delete(id);
        // Clean up TODO state cache
        this.todosCache.delete(id);
        // Clean up side-turns cache
        this.quickAskTurnsCache.delete(id);
        // Clean up generated-asset cache
        this.toolCallAssetsCache.delete(id);

        // Save list.json after successful memory deletion — must go through
        // the write chain so concurrent background saves do not race.
        //
        // IMPORTANT: saveMetadata() runs BEFORE clearing _activeSessionId
        // so the on-disk list.json never contains activeSessionId: "".
        // When wasActive is true the stored id points to a now-absent
        // session; loadFromCache() handles this gracefully via its
        // metadataMap.has() guard and falls back to the constructor-
        // created default. The caller MUST re-establish a valid active
        // session (via switchTo() or createSession()) after this call.
        await this.saveMetadata();

        if (wasActive) {
            this._activeSessionId = '';
        }

        // Delete messages file (failure is non-critical)
        try {
            const adapter = this.app.vault.adapter;
            const msgPath = `${this.sessionsDir}/${id}.json`;
            if (await adapter.exists(msgPath)) {
                await adapter.remove(msgPath);
            }
            // Also clean up the session's artifacts subdirectory (if any).
            const artifactsDir = `${this.sessionsDir}/${id}`;
            if (await adapter.exists(artifactsDir)) {
                // Delete individual files first, then rmdir.
                try {
                    const listing = await adapter.list(artifactsDir);
                    for (const file of listing.files) {
                        await adapter.remove(`${artifactsDir}/${file}`);
                    }
                    for (const folder of listing.folders) {
                        // Recursively clean up nested dirs (paranoid; shouldn't exist).
                        try { await adapter.rmdir(`${artifactsDir}/${folder}`, true); } catch { /* ignore */ }
                    }
                } catch { /* best-effort listing; continue to rmdir anyway */ }
                try { await adapter.rmdir(artifactsDir, false); } catch { /* may have been removed already */ }
            }
        } catch (error) {
            console.warn('[SessionManager] Failed to delete messages file:', error);
        }

        return true;
    }

    /**
     * Delete all sessions except the current active session.
     *
     * The currently active session is *always* preserved. When
     * `excludeIds` is provided, those additional session IDs are also
     * skipped — the typical use case is letting the user opt out of
     * deleting sessions whose runtime is currently mid-turn (busy).
     *
     * Returns the number of sessions actually deleted.
     */
    async deleteAllHistorySessions(excludeIds?: ReadonlySet<string>): Promise<number> {
        const sessionsToDelete = Array.from(this.metadataMap.keys()).filter(
            id => id !== this._activeSessionId && !(excludeIds?.has(id))
        );

        if (sessionsToDelete.length === 0) {
            return 0;
        }

        let deletedCount = 0;

        for (const sessionId of sessionsToDelete) {
            if (await this.deleteSession(sessionId)) {
                deletedCount++;
            }
        }

        return deletedCount;
    }

    /**
     * Append a unit of work to the serialised write chain.
     *
     * Every call to {@link saveMetadata}, {@link saveToCache},
     * {@link switchTo}, and {@link deleteSession} flows through here so
     * list.json is never written concurrently.  The `.then(fn, fn)`
     * dual-handler ensures a single failing write (e.g. disk full) does
     * not poison the chain — subsequent callers still execute their own
     * work.
     *
     * The work function reads `_activeSessionId`, `_nextId`, and
     * `metadataMap` at call time, which is *after* every preceding chain
     * entry has completed.  This eliminates the TOCTOU gap that existed
     * in the old `savePromise`-based mutex pattern.
     */
    private enqueueWrite(work: () => Promise<void>): Promise<void> {
        const next = this.writeChain.then(work, work);
        this.writeChain = next;
        return next;
    }

    /**
     * Save only the list.json file (session metadata).
     *
     * Appended to {@link writeChain} so concurrent callers (draft flush,
     * new-session creation, background runtime turn-finish, title gen,
     * insight extraction) never race on list.json.  The writer reads
     * `_activeSessionId` and `metadataMap` right before performing I/O,
     * after any preceding chain entry has completed, so state changes
     * made by an earlier writer are always visible.
     */
    async saveMetadata(): Promise<void> {
        await this.enqueueWrite(() => this.saveListFile());
    }

    /** Save only the list.json file (session metadata) */
    private async saveListFile(): Promise<void> {
        try {
            const adapter = this.app.vault.adapter;

            // Ensure sessions directory exists
            if (!await adapter.exists(this.sessionsDir)) {
                await adapter.mkdir(this.sessionsDir);
            }

            const listData: SessionListFile = {
                version: 1,
                activeSessionId: this._activeSessionId,
                nextId: this._nextId,
                sessions: Array.from(this.metadataMap.values()),
            };

            await adapter.write(this.listFilePath, JSON.stringify(listData, null, 2));
        } catch (error) {
            console.warn('[SessionManager] Failed to save list file:', error);
        }
    }

    /** Load messages for a specific session (lazy load) */
    private async loadMessages(id: string): Promise<void> {
        if (this.loadedMessages.has(id)) return;

        const meta = this.metadataMap.get(id);
        if (!meta) return;

        try {
            const adapter = this.app.vault.adapter;
            const msgPath = `${this.sessionsDir}/${id}.json`;

            if (await adapter.exists(msgPath)) {
                const content = await adapter.read(msgPath);
                // Use a permissive type for version-gating — the real
                // SessionMessagesFile type has version: 5|6|7 so TS would
                // reject comparisons with 1–4 below.
                const raw = JSON.parse(content) as { version: number; id: string } & Record<string, unknown>;

                // Reject v1–v4 sessions: purge the stale file and remove
                // metadata so the session disappears from the list.
                if (raw.version >= 1 && raw.version <= 4) {
                    console.warn(`[SessionManager] Session ${id} has deprecated cache version ${raw.version}, purging`);
                    await adapter.remove(msgPath);
                    this.metadataMap.delete(id);
                    this.messagesCache.set(id, []);
                } else if ((raw.version === 5 || raw.version === 6 || raw.version === 7) && raw.id === id) {
                    const data = raw as unknown as SessionMessagesFile;
                    this.messagesCache.set(id, data.messages);
                    // Load summaries if present (for context compression)
                    if (data.summaries && Array.isArray(data.summaries)) {
                        this.summariesCache.set(id, data.summaries);
                    }
                    // Load sub-agent messages (v5+ only)
                    if (data.subAgentMessages && typeof data.subAgentMessages === 'object') {
                        this.subAgentMessagesCache.set(id, data.subAgentMessages);
                    }
                    // Load per-agent token usage breakdown (v5+ only)
                    if (data.agentTokenBreakdown && typeof data.agentTokenBreakdown === 'object'
                        && data.agentTokenBreakdown.main && data.agentTokenBreakdown.subAgents) {
                        this.agentTokenBreakdownCache.set(id, data.agentTokenBreakdown);
                    }
                    // Load TODO state (v5+ only). Validate shape defensively
                    // so a corrupt or partial file can't poison the runtime.
                    if (data.todos
                        && typeof data.todos === 'object'
                        && Array.isArray(data.todos.items)
                        && data.todos.items.length > 0) {
                        this.todosCache.set(id, {
                            items: data.todos.items.map((item) => ({
                                id: String(item.id ?? ''),
                                brief: typeof item.brief === 'string' ? item.brief : '',
                                content: typeof item.content === 'string' ? item.content : '',
                                status: item.status ?? 'pending',
                                createdAt: typeof item.createdAt === 'number' ? item.createdAt : Date.now(),
                                updatedAt: typeof item.updatedAt === 'number' ? item.updatedAt : Date.now(),
                            })),
                            updatedAt: typeof data.todos.updatedAt === 'number'
                                ? data.todos.updatedAt
                                : Date.now(),
                        });
                    }
                    // Load QuickAsk side-turns (v6+ only). Validate shape
                    // defensively so a corrupt or partial file can't poison
                    // the UI.
                    if (data.quickAskTurns
                        && Array.isArray(data.quickAskTurns)
                        && data.quickAskTurns.length > 0) {
                        this.quickAskTurnsCache.set(id, data.quickAskTurns.map(t => ({ ...t })));
                    }
                    // Load generated-asset records (v7+ only). Validate
                    // shape defensively.
                    if (data.toolCallAssets
                        && Array.isArray(data.toolCallAssets)
                        && data.toolCallAssets.length > 0) {
                        this.toolCallAssetsCache.set(id, [...data.toolCallAssets]);
                    }
                } else {
                    console.warn('[SessionManager] Invalid messages file format:', id);
                    this.messagesCache.set(id, []);
                }
            } else {
                this.messagesCache.set(id, []);
            }

            this.loadedMessages.add(id);
        } catch (error) {
            console.warn('[SessionManager] Failed to load messages:', error);
            this.messagesCache.set(id, []);
            this.loadedMessages.add(id);
        }
    }

    /** Save messages for a specific session to file */
    private async saveMessages(id: string): Promise<void> {
        if (!this.loadedMessages.has(id)) return;

        const messages = this.messagesCache.get(id);
        if (messages === undefined) return;

        try {
            const adapter = this.app.vault.adapter;

            // Ensure sessions directory exists
            if (!await adapter.exists(this.sessionsDir)) {
                await adapter.mkdir(this.sessionsDir);
            }

            // Get summaries for this session (may be empty)
            const summaries = this.summariesCache.get(id);
            // Get sub-agent messages for this session (may be absent)
            const subAgentMessages = this.subAgentMessagesCache.get(id);
            const hasSubAgentData = subAgentMessages && Object.keys(subAgentMessages).length > 0;
            // Get per-agent token usage breakdown for this session (may be absent)
            const agentTokenBreakdown = this.agentTokenBreakdownCache.get(id);
            const hasBreakdownData = !!agentTokenBreakdown
                && (Object.keys(agentTokenBreakdown.subAgents).length > 0
                    || agentTokenBreakdown.main.totalTokens > 0);
            // Get TODO state for this session (may be absent / empty)
            const todos = this.todosCache.get(id);
            const hasTodoData = !!todos && todos.items.length > 0;
            // Get QuickAsk side-turns for this session (v6+)
            const quickAskTurns = this.quickAskTurnsCache.get(id);
            const hasQuickAskTurnsData = !!quickAskTurns && quickAskTurns.length > 0;
            // Get generated-asset records for this session (v7+)
            const toolCallAssets = this.toolCallAssetsCache.get(id);
            const hasToolCallAssetsData = !!toolCallAssets && toolCallAssets.length > 0;

            // Pick the minimal schema version that encodes all present
            // fields. Newer fields force the version up so older builds
            // refuse to overwrite a file they don't understand.
            // v1–v4 are deprecated; the minimum writable version is v5.
            const version: 5 | 6 | 7 = hasToolCallAssetsData
                ? 7
                : hasQuickAskTurnsData
                    ? 6
                    : 5;

            const data: SessionMessagesFile = {
                version,
                id,
                messages,
                toolCallAssets: hasToolCallAssetsData ? toolCallAssets : undefined,
                summaries: summaries && summaries.length > 0 ? summaries : undefined,
                subAgentMessages: hasSubAgentData ? subAgentMessages : undefined,
                agentTokenBreakdown: hasBreakdownData ? agentTokenBreakdown : undefined,
                todos: hasTodoData ? todos : undefined,
                quickAskTurns: hasQuickAskTurnsData ? quickAskTurns : undefined,
            };

            const msgPath = `${this.sessionsDir}/${id}.json`;
            await adapter.write(msgPath, JSON.stringify(data, null, 2));
        } catch (error) {
            console.warn('[SessionManager] Failed to save messages:', error);
        }
    }

    /** Ensure messages for the active session are loaded */
    async ensureActiveMessagesLoaded(): Promise<void> {
        await this.loadMessages(this._activeSessionId);
    }

    /** Ensure messages for a specific session are loaded */
    async ensureMessagesLoaded(id: string): Promise<void> {
        await this.loadMessages(id);
    }

    // ── Persistence ──────────────────────────────────────────────────────────

    /**
     * Load sessions metadata from list file. Called once at startup.
     * Messages are loaded on demand.
     */
    async loadFromCache(): Promise<void> {
        if (this.cacheLoaded) return;

        try {
            const adapter = this.app.vault.adapter;
            const exists = await adapter.exists(this.listFilePath);

            if (!exists) {
                this.cacheLoaded = true;
                return;
            }

            const content = await adapter.read(this.listFilePath);
            const data = JSON.parse(content) as SessionListFile;

            // Validate cache version
            if (data.version !== 1) {
                console.warn('[SessionManager] Unknown cache version, ignoring cache');
                this.cacheLoaded = true;
                return;
            }

            // Restore session metadata
            this.metadataMap.clear();
            this.messagesCache.clear();
            this.summariesCache.clear();
            this.subAgentMessagesCache.clear();
            this.agentTokenBreakdownCache.clear();
            this.todosCache.clear();
            this.quickAskTurnsCache.clear();
            this.toolCallAssetsCache.clear();
            this.loadedMessages.clear();

            for (const meta of data.sessions) {
                // Migration: ensure firstUserMessage exists for old sessions
                if (meta.firstUserMessage === undefined) {
                    meta.firstUserMessage = '';
                }
                this.metadataMap.set(meta.id, meta);
            }

            // Purge sessions with deprecated v1–v4 cache files, so they
            // never appear in the session list. Remove from metadataMap
            // and delete the backing file.
            let purgedCount = 0;
            for (const [id] of this.metadataMap) {
                const msgPath = `${this.sessionsDir}/${id}.json`;
                if (await adapter.exists(msgPath)) {
                    try {
                        const content = await adapter.read(msgPath);
                        const sessionData = JSON.parse(content) as { version: number };
                        if (sessionData.version >= 1 && sessionData.version <= 4) {
                            console.warn(`[SessionManager] Purging deprecated v${sessionData.version} session: ${id}`);
                            await adapter.remove(msgPath);
                            this.metadataMap.delete(id);
                            purgedCount++;
                        }
                    } catch {
                        // Corrupt file — also purge
                        console.warn(`[SessionManager] Purging corrupt session file: ${id}`);
                        await adapter.remove(msgPath);
                        this.metadataMap.delete(id);
                        purgedCount++;
                    }
                }
            }

            // If any sessions were purged, persist the updated list so
            // stale entries are cleaned from disk.
            if (purgedCount > 0) {
                await this.saveMetadata();
            }

            // Restore active session ID if valid
            if (data.activeSessionId && this.metadataMap.has(data.activeSessionId)) {
                this._activeSessionId = data.activeSessionId;
                // Pre-load active session messages
                await this.loadMessages(this._activeSessionId);
            }

            // Restore next ID counter
            if (typeof data.nextId === 'number' && data.nextId > 1) {
                this._nextId = data.nextId;
            }

            // Load global token statistics after sessions are restored (so
            // the fallback can recompute from metadata if the file is absent
            // or corrupt — first-run migration for existing users).
            await this._loadGlobalStatistics();

            this.cacheLoaded = true;
        } catch (error) {
            console.warn('[SessionManager] Failed to load cache:', error);
            this.cacheLoaded = true;
        }
    }

    /**
     * Load global cumulative token statistics from statistics.json.
     * Falls back to recomputing from all session metadata when the file
     * is absent, has an unknown version, or is corrupt.
     */
    private async _loadGlobalStatistics(): Promise<void> {
        const adapter = this.app.vault.adapter;
        try {
            if (await adapter.exists(this.statisticsFilePath)) {
                const content = await adapter.read(this.statisticsFilePath);
                const stats = JSON.parse(content) as GlobalTokenStatisticsFile;
                if (stats.version === 1
                    && typeof stats.promptTokens === 'number'
                    && typeof stats.completionTokens === 'number'
                    && typeof stats.totalTokens === 'number') {
                    this._globalTokenStats = {
                        promptTokens: stats.promptTokens,
                        completionTokens: stats.completionTokens,
                        totalTokens: stats.totalTokens,
                    };
                    return;
                }
            }
        } catch {
            // File absent or corrupt — fall through to recompute.
        }

        // Fallback: recompute from all session metadata (first-run migration).
        let p = 0, c = 0, t = 0;
        for (const meta of this.metadataMap.values()) {
            p += meta.tokenUsage.promptTokens;
            c += meta.tokenUsage.completionTokens;
            t += meta.tokenUsage.totalTokens;
        }
        this._globalTokenStats = { promptTokens: p, completionTokens: c, totalTokens: t };
    }

    /**
     * Save all session metadata to list file and save all loaded messages.
     * Called after each complete conversation round.
     * 
     * Appended to {@link writeChain} so this call is serialised with all
     * other writers (saveMetadata, switchTo, deleteSession).
     */
    async saveToCache(): Promise<void> {
        await this.enqueueWrite(() => this._doSaveToCache());
    }

    /**
     * Internal implementation of saveToCache.
     * Should only be called through saveToCache() to ensure proper locking.
     */
    private async _doSaveToCache(): Promise<void> {
        try {
            const adapter = this.app.vault.adapter;

            // Ensure sessions directory exists
            if (!await adapter.exists(this.sessionsDir)) {
                await adapter.mkdir(this.sessionsDir);
            }

            // Save metadata list
            const listData: SessionListFile = {
                version: 1,
                activeSessionId: this._activeSessionId,
                nextId: this._nextId,
                sessions: Array.from(this.metadataMap.values()),
            };

            await adapter.write(this.listFilePath, JSON.stringify(listData, null, 2));

            // Save global token statistics
            const statsData: GlobalTokenStatisticsFile = {
                version: 1,
                promptTokens: this._globalTokenStats.promptTokens,
                completionTokens: this._globalTokenStats.completionTokens,
                totalTokens: this._globalTokenStats.totalTokens,
            };
            await adapter.write(this.statisticsFilePath, JSON.stringify(statsData, null, 2));

            // Save all loaded messages to individual files
            for (const id of this.loadedMessages) {
                await this.saveMessages(id);
            }
        } catch (error) {
            console.warn('[SessionManager] Failed to save cache:', error);
        }
    }
}
