/**
 * Session manager data schemas and types.
 *
 * Extracted from session-manager.ts to keep the class lean.
 */

import type { ChatMessage, ConversationSummary, AgentTokenBreakdown, QuickAskTurn } from './services/chat-stream';
import type { TokenUsage } from './services/llm-provider';
import type { InsightCardState } from './services/insights';
import type { SuggestionCardState } from './services/suggestions';
import type { TodoState } from './services/tools/todo-state';
import type { GeneratedAsset } from './services/generated-asset-collection';

export type ReadonlyChatMessages = ReadonlyArray<ChatMessage>;

/** Session metadata (stored in list.json) */
export interface SessionMetadata {
    id: string;
    /** Session title, empty string means "use firstUserMessage as display title" */
    title: string;
    /** First user message content (truncated for display), stored for quick access without loading full messages */
    firstUserMessage: string;
    tokenUsage: TokenUsage;
    createdAt: number;
    updatedAt: number;
    /**
     * Schema version of the session messages file (sessions/{id}/messages.json).
     * Mirrors {@link SessionMessagesFile.version}. Stored in list.json so
     * the startup purge check does NOT need to read every session file
     * just to detect deprecated v1–v4 formats. Absent for metadata
     * written by older plugin versions — in that case a one-time file
     * read is still performed to discover the version.
     */
    messageVersion?: number;
    /** Draft input content (unsent text in input box), restored when loading session */
    draftInput?: string;
    /**
     * Last terminal state of the insight preview card. Persisted by
     * {@link SessionRuntime} after each successful (or failed) insight
     * extraction so that switching away and back to the session — or
     * reloading the plugin entirely — restores the card without
     * re-running the LLM call. Bound to a specific assistant
     * `messageId` so stale states are detectable on replay.
     *
     * `loading` is deliberately not persisted (it's transient).
     */
    lastInsights?: InsightCardState;

    /**
     * Last terminal state of the follow-up suggestion bar, produced
     * by the LLM fallback extraction. Persisted by {@link SessionRuntime}
     * so the bar survives view detach and plugin reload. Mirrors
     * {@link lastInsights} in shape and lifecycle.
     */
    lastSuggestions?: SuggestionCardState;
}

/** Messages file content (stored in sessions/${id}/messages.json) */
export interface SessionMessagesFile {
    /**
     * File schema version.
     * - v1–v4: deprecated. Sessions with these versions are purged on
     *          load (file deleted, metadata removed).
     * - v5: reshapes each TODO item to carry TWO required strings —
     *       `brief` (short user-facing summary) and `content` (long
     *       machine-facing task spec).
     * - v6: adds `quickAskTurns` (QuickAsk side-conversation pairs persisted
     *       separately from the main message flow).
     * - v7: adds `toolCallAssets` (top-level session field listing assets
     *       generated by tool calls, moved from ChatMessage.toolCallAssets).
     */
    version: 5 | 6 | 7;
    id: string;
    messages: ChatMessage[];
    /** Top-level generated-asset records (v7+). Peer to messages, moved
     *  from per-message `toolCallAssets` to a session-level collection. */
    toolCallAssets?: GeneratedAsset[];
    /** Conversation summaries for context compression (persisted separately from messages) */
    summaries?: ConversationSummary[];
    /**
     * Sub-agent messages produced during delegate_task invocations, keyed by
     * the parent delegate_task toolCallId. Used by the UI to re-render inline
     * sub-agent bubbles after a session reload.
     */
    subAgentMessages?: Record<string, ChatMessage[]>;
    /**
     * Per-agent token usage split (main + each sub-agent by name).
     * Only produced by multi-agent sessions; absent for single-agent
     * (ChatStream) sessions.
     */
    agentTokenBreakdown?: AgentTokenBreakdown;
    /**
     * TODO state maintained by the `manage_todos` tool. Persisted so
     * the pinned panel + the model's view of in-progress subtasks
     * survive reloads. Absent / empty list is treated as "no todos"
     * by the loader.
     */
    todos?: TodoState;
    /**
     * QuickAsk side-turns persisted separately from the main message
     * flow. Each entry is a user→assistant question/answer pair
     * anchored to a specific assistant message. Absent in v5
     * files (treated as empty). Added in v6.
     */
    quickAskTurns?: QuickAskTurn[];
}

/** List file content (stored in sessions/list.json) */
export interface SessionListFile {
    version: 1;
    nextId: number;
    sessions: SessionMetadata[];
}

/** Global cumulative token statistics (stored in sessions/statistics.json) */
export interface GlobalTokenStatisticsFile {
    version: 1;
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
    cachedPromptTokens: number;
}

/** Snapshot of a session (full data for backward compatibility with public API) */
export interface SessionSnapshot {
    id: string;
    title: string;
    firstUserMessage: string;
    messages: ChatMessage[];
    tokenUsage: TokenUsage;
    createdAt: number;
    updatedAt: number;
}
